name: Everyday_azure_request

on:
  schedule:
     - cron: '3 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#       - name: Lint with flake8
#         run: |
#           pip install flake8
#           flake8 .
          
      - name: Checkout the python version
        run: python -c "import sys; print(sys.version)"
      
#       - name: Running my script
#         run: |
#           python queue_python.py
