name: Everyday azure check

on: [push]
# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#   - cron: '0 15 * * *' # check on 15:00 UTC everyday
#   - cron: '0/20 22 * * *' 
#   - cron: '* * * * *' # check on every 10 mins
jobs:
  auto_checkout_Azure:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v1
      with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
#     - name: Checkout the python version
#       run: |
#         python -c 'import sys; print(sys.version)'

    
    - name: Running Azure script
      run: |
        python queue_python.py
        
  sending_Slack_message:
    needs: auto_checkout_Azure
    if: success()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Sending message to Slack     
      run: |
          python gitslack.py ${{ secrets.SLACK_PRIVATE_URL }}
